### PR TITLE
change license to BSD

### PR DESCRIPTION
**Pull request by pdebuyl**
Hi @petercolberg do you approve change of license?

### CODE REVIEW

**Comment by petercolberg** [comment]
On Fri, Nov 27, 2015 at 05:11:04AM -0800, Pierre de Buyl wrote:
>   * change license to BSD

Could you revise the commit to clarify the license name?

This looks like BSD-3-clause.

https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-specification

**Comment by pdebuyl** [comment]
This way?

**Comment by petercolberg** [comment]
On Fri, Nov 27, 2015 at 01:03:27PM -0800, Pierre de Buyl wrote:
> This way?

ParseText.f90 still says `License: BSD`.

You can merge the commits using something like

# git rebase -i origin/master

and prefixing all commits except the first with `fixup`.

**Comment by pdebuyl** [comment]
else, `git push --force` is ok on dev branches no?

**Comment by petercolberg** [comment]
On Fri, Nov 27, 2015 at 01:28:02PM -0800, Pierre de Buyl wrote:
> else, `git push --force` is ok on dev branches no?

Yes, absolutely.

In fact, you could use a separate branch for each pull request, and
force-push to your heart’s delight until the commit(s) are right.

I find it valuable to be have a clear history for later reference,
where each commit implements one logical thing and does it well.

**Comment by pdebuyl** [comment]
Still, the original question was, as having contributed to the code do you agree with the change of license? :-)

**Comment by petercolberg** [comment]
Please merge the commits into one commit once more…

**Comment by pdebuyl** [comment]
So?

**Comment by petercolberg** [comment]
D’accord.

**Comment by pdebuyl** [comment]
Thanks!

**Pull request merged**
